global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "monitoring"
    static_configs:
      - targets:
          # Prometheus can access the golang application running on app:8000 because docker-compose takes care of dns
          # resolving.
          - app:8000
          # Allow prometheus to scrape itself.
          - localhost:9090
