{
 "title": "HTTP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "status_rate_interval", "label": "status_rate_interval", "query": "1m,5m,10m,30m,1h,3h,24h" },
   { "name": "latency_rate_interval", "label": "latency_rate_interval", "query": "1m,5m,10m,30m,1h,3h,24h" }
  ]
 },
 "panels": [
  {
   "title": "Htpp request latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(app_request_duration_seconds_bucket[$latency_rate_interval])))",
     "legendFormat": "99% percentile "
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(app_request_duration_seconds_bucket[$latency_rate_interval])))",
     "legendFormat": "90% percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(app_request_duration_seconds_bucket[$latency_rate_interval])))",
     "legendFormat": "50% percentile"
    }
   ]
  },
  {
   "title": "Tags requested",
   "type": "timeseries",
   "description": "The count of tags requested within a time period",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(app_handler_tags_get_count[5m])",
     "legendFormat": "{{tags}}"
    }
   ]
  },
  {
   "title": "HTTP status rate",
   "type": "timeseries",
   "description": "Shows metrics about the status  rate of HTTP requests",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(app_requests_total[$status_rate_interval])",
     "legendFormat": "{{method}} {{url}} - {{code}} - {{host}}"
    }
   ]
  }
 ]
}