{
 "title": "HTTP status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "status_rate_interval", "label": "status_rate_interval", "query": "1m,5m,10m,30m,1h,3h,24h" }
  ]
 },
 "panels": [
  {
   "title": "App version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "info", "legendFormat": "{{version}}  {{sha}}" }
   ]
  },
  {
   "title": "Tags requested",
   "type": "timeseries",
   "description": "The count of tags requested within a time period",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(app_handler_tags_get_count[5m])",
     "legendFormat": "{{tags}}"
    }
   ]
  },
  {
   "title": "HTTP status rate",
   "type": "timeseries",
   "description": "Shows metrics about the status  rate of HTTP requests",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(app_requests_total[$status_rate_interval])",
     "legendFormat": "{{method}} {{url}} - {{code}} - {{host}}"
    }
   ]
  }
 ]
}