development:
  dialect: postgres
  datasource: host=${DATABASE_HOST} port=${DATABASE_PORT} dbname=${DATABASE_NAME} user=${DATABASE_USER} password=${DATABASE_PASSWORD} sslmode=disable
  dir: .
  table: migrations
